// models/Pandit.js
import mongoose from "mongoose";
import bcrypt from "bcryptjs";

const panditSchema = new mongoose.Schema(
  {
    name: { type: String, required: [true, "Pandit name is required"], trim: true },
    dob: { type: Date, required: [true, "Date of birth is required"] },
    gender: { type: String, required: [true, "Gender is required"], enum: ["Male", "Female", "Other"] },

    languages: { type: [String], required: [true, "At least one language is required"] },
    skills: { type: [String], required: [true, "At least one skill is required"] },
    otherSkill: { type: String, trim: true },

    email: {
      type: String,
      required: [true, "Email is required"],
      unique: true,
      lowercase: true,
      trim: true,
      match: [/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/, "Please provide a valid email address"],
      index: true,
    },

    // 🔑 Password optional for now
    password: {
      type: String,
      minlength: [6, "Password must be at least 6 characters long"],
      select: false,
      required: false,
    },

    image: { type: String, default: "default_pandit.png" },

    status: {
      type: String,
      enum: ["pending", "approved", "rejected", "inactive"],
      default: "pending",
    },

    createdByAdmin: { type: Boolean, default: false },
    isVerified: { type: Boolean, default: false },

    /* 🧩 -------- Admin Portal Extensions -------- */
    approved: { type: Boolean, default: false }, // redundant but useful for admin filters
    credentials: {
      panditId: { type: String, default: null }, // generated by admin
      passwordHash: { type: String, default: null }, // if admin manually creates
    },
    earnings: { type: Number, default: 0 }, // total earned (lifetime)
    balance: { type: Number, default: 0 }, // unpaid amount (for salary payouts)
    rating: { type: Number, default: 0 },
    lastLogin: { type: Date, default: null },
    suspended: { type: Boolean, default: false },
    adminNotes: { type: String, trim: true },
  },
  { timestamps: true, versionKey: false }
);

// ✅ Password hashing middleware (only if password exists)
panditSchema.pre("save", async function (next) {
  if (!this.isModified("password") || !this.password) return next();
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
  next();
});

// 🔒 Compare password (for Pandit login)
panditSchema.methods.matchPassword = async function (enteredPassword) {
  return bcrypt.compare(enteredPassword, this.password);
};

const Pandit = mongoose.model("Pandit", panditSchema);
export default Pandit;
